HomeSummary: An advanced purely-functional programming language
HomeTag: Declarative, statically typed code.
HomeCodeSample: This example is contrived in order to demonstrate what Haskell looks like, including: (1) where syntax, (2) enumeration syntax, (3) pattern matching, (4) consing as an operator, (5) list comprehensions, (6) infix functions. Don't take it seriously as an efficient prime number generator.
HomeGot5Minutes: Got 5 Minutes?
HomeTypeHelp: Type <code title="Click me to insert &quot;help&quot; into the console." style="cursor: pointer;">help</code> to start the tutorial.
HomeTryTheseOut: Or try typing these out and see what happens
HomeClickToInsert: click to insert