HomeSummary: Uma linguagem de programação puramente-funcional
HomeTag: Código declarativo, estáticamente tipado
HomeCodeSample: Esse exemplo é complexo para demonstrar como Haskell se parece, incluindo: (1) sintaxe where, (2) sinxaxe de enumerações, (3) pattern matching, (4) consing como um operador, (5) list comprehensions, (6) funções infixas. Não o leve a sério como um gerador de números primos eficiente.
HomeGot5Minutes: Tem 5 minutos?
HomeTypeHelp: Digite <code title="Clique em mim para inserir &quot;help&quot; no console." style="cursor: pointer;">help</code> para começar o tutorial.
HomeTryTheseOut: Ou tente digitar essas expressões e veja o que acontece
HomeClickToInsert: clique para inserir